spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/sb_study_kyy
    username: root
    password: 1q2w3e4r

jwt:
  secret: afed7133b413b55f69c07c840728af6089b6c7f17f3e94d7b0ee3ad94e684e62ff168b6c9f0a2d6c0d4fc7e51ae57b3ec83e2b49ff179482820a48257cde99d7


springdoc:
  swagger-ui:
    path: doc

# application.yml ?? (??? ??)

mybatis:
  # 1. XML Mapper ?? ?? ??
  mapper-locations: classpath:mapper/**/*.xml

  # 2. Type Alias? ??? ??? ?? (mybatis ?? ?? ?? ??)
  type-aliases-package: com.korit.springboot.entity

  # 3. MyBatis Configuration ?? (mybatis ?? ?? ?? ??)
  configuration:
    # 4. ?? ?? (configuration ?? ??)
    map-underscore-to-camel-case: true
